version: '3' # compose ファイルの書式バージョン
services:
  login-demo: # demo-app という名前でサービスを定義
    build: . # 指定パスの Dockerfile を参照
    volumes: # コンテナ内で作成したデータの永続化用
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホスト:コンテナ のポートを紐づけ
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'login-demo'  # 初期データベースとしてdemoを設定
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306  # ホストマシンのポート33306を、docker内のポート3306に接続する
volumes:
  mysql_data: